name: Publish Docker

on:
  push:
    branches: [ master ]

env:
  REACT_APP_API: ${{ vars.REACT_APP_API }}
  GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API: ${{ vars.REACT_APP_API }}
      GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        env:
          REACT_APP_API: ${{ vars.REACT_APP_API }}
          GENERATE_SOURCEMAP: ${{ vars.GENERATE_SOURCEMAP }}
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: AndreyOtin/comp-shop/image
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
